[tools]
## Stack
node = { version = "lts", postinstall = "corepack enable" }
rust = "latest"

[settings]
# Enable extra features
experimental = true
# Consume Node.js version from .nvmrc, .tool-versions, etc.
idiomatic_version_file_enable_tools = ["node", "rust"]

[tasks.dev]
description = "Run development server"
run = "pnpm -F @chessboard.pro/web dev"

[env]
# Default account ID, use .env.local to override
CLOUDFLARE_ACCOUNT_ID = "a882f484593b0536f22686b11f8ccc05"
# NOTE: Keep it as the last line to ensure it loads after other env vars
'_'.file = { path = ".env" }
