// Generated by Wrangler
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

// Note: This file is intended to be generated by `wrangler types`.
// If you edit it manually, remember it may be overwritten.

declare namespace Cloudflare {
  interface Env {
    NEXTJS_ENV: string;
    NEXT_INC_CACHE_R2_BUCKET: R2Bucket;
    WORKER_SELF_REFERENCE: Service<typeof import("./.open-next/worker").default>;
    ASSETS: Fetcher;
  }
}

interface CloudflareEnv extends Cloudflare.Env {}
